### PR TITLE
Add Test Coverage for DCSRoleCoreBundle

### PR DESCRIPTION
**Pull request by jmauerhan**
- Provides coverage of DCSRoleCoreBundle.php , taking overall coverage to 34.38% (of all lines)

### CODE REVIEW

**Comment by damianociarla** [comment]
Hi @jmauerhan,
I encountered this warning when I try to run the tests:

1) DCS\Role\CoreBundle\Tests\DCSRoleCoreBundleTest::testBuildAddsProviderCompilerPass
Cannot mock Symfony\Component\DependencyInjection\ContainerBuilder::addExpressionLanguageProvider() because a class or interface used in the signature is not loaded

**Comment by jmauerhan** [comment]
I'll look into it - did you run from the vendor phpunit? vendor/bin/phpunit instead of a globally installed version?

Have you thought about setting up travis or circle ci? That would make it easier to see errors too.

**Comment by jmauerhan** [comment]
I'm not able to reproduce this, and my research shows it may be due to using an older version of phpunit, so I think you may be running a globally installed version instead of the latest which I put in vendor.

**Comment by damianociarla** [comment]
Hi @jmauerhan ,
I thank you for your support! I ran the tests on a server with php7 and everything seems to work properly :-)

**Comment by jmauerhan** [comment]
My pleasure! :) I am planning on adding some more - do you need some help getting CI set up? Travis is super easy to use and free.

**Comment by damianociarla** [comment]
Would be great! I learn something new :-)

**Comment by jmauerhan** [comment]
Cool - Travis is easy, you just login with github - you have to be an admin on the repo to add it, but then once you've added it to Travis, I can help with the config file and get tests running. 

Just go to https://travis-ci.org/ and login with github, then click the little plus next to "My Repositories".

**Pull request merged**
